//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ckeditor_with_image_upload_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articles
    {
        public int Article_Id { get; set; }
        public string Article_Title { get; set; }
        public string Article_Content { get; set; }
    }
}
